# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 A.U.R.O.R.A. Project
"""The code of conduct, enforced and protected (sys/core/ethics/CODE.md).

Integrity: MANIFEST.json holds the SHA-256 of the protected files and an Ed25519 signature
of them by the owner's key. Every installation has its own key pair, generated by the installer
as root in /etc/aurora: the private half readable by root only, the public half trusted only while
root owns it and nobody else can change it. Aurora's services run as another user, so they can
neither sign nor swap the key. A changed file without a new signature, or a
missing or invalid manifest, stops every service at start: Aurora does not run with rules
that were changed without the owner. No open-source program can stop someone from removing
this check from their own copy; it makes any change to the rules deliberate and evident.

Level A (always, for everyone): capabilities a plugin may never have.
Level B (by default): external actions and code changes wait for the owner, AI disclosure on.
The owner of an installation may exempt it from level B by a file signed with that
installation's key for this machine and folder only (AURORA_ETHICS_EXEMPTION, never committed).
Level A has no exemption.
"""
from __future__ import annotations

import hashlib
import json
import sys
from functools import lru_cache
from pathlib import Path

from . import sys_config

KEY_DIR = Path("/etc/aurora")                       # one key pair per installation, made by the installer as root
PRIVATE_KEY = KEY_DIR / "owner_ed25519"
PUBLIC_KEY = KEY_DIR / "owner_ed25519.pub"
CODE_ROOT = Path(__file__).resolve().parents[3]
PROTECTED = ("sys/core/ethics/CODE.md", "sys/core/aurora/sys_ethics.py", "sys/core/aurora/plg_host.py",
             "sys/core/aurora/sys_approvals.py", "sys/core/aurora/sys_disclosure.py", "sys/core/aurora/agt_change.py",
             "sys/core/aurora/plg_sandbox.py")
MANIFEST = "sys/core/ethics/MANIFEST.json"
FORBIDDEN = {"offensive_scan", "exploit", "denial_of_service", "person_lookup", "person_tracking",
             "credential_attack", "malware", "unauthorized_access", "impersonation"}
EXEMPT_PURPOSE = "aurora-ethics-level-B-exempt"


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _canonical(files: dict) -> bytes:
    return json.dumps(files, sort_keys=True, separators=(",", ":")).encode()


def owner_public_key(path: Path | None = None) -> tuple[str, str]:
    """(public key hex, problem). Trusted only if root owns the file and its folder and nobody else
    can write them: a key Aurora could replace would protect nothing."""
    p = path or PUBLIC_KEY
    try:
        for x in (p.parent, p):
            st = x.stat()                                  # follows links: a link to a user's file fails here
            if st.st_uid != 0 or st.st_mode & 0o022:
                return "", f"{x} must belong to root and be writable by root only"
        text = p.read_text().strip()
        if len(bytes.fromhex(text)) != 32:
            raise ValueError
    except OSError:
        return "", f"no owner key at {p} (run: sudo .venv/bin/python sys/core/script/sys_ethics_sign.py setup)"
    except ValueError:
        return "", f"{p} is not an Ed25519 public key"
    return text, ""


def _verify(message: bytes, signature_hex: str, public_hex: str) -> bool:
    from cryptography.exceptions import InvalidSignature
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
    try:
        key = Ed25519PublicKey.from_public_bytes(bytes.fromhex(public_hex))
        key.verify(bytes.fromhex(signature_hex), message)
        return True
    except (InvalidSignature, ValueError):
        return False


def integrity(root: Path = CODE_ROOT, public_hex: str = "") -> tuple[bool, str]:
    """(intact, reason): every protected file matches the signed manifest."""
    if not public_hex:
        public_hex, problem = owner_public_key()
        if not public_hex:
            return False, problem
    mf = root / MANIFEST
    if not mf.exists():
        return False, f"{MANIFEST} missing (run sys_ethics_sign.py sign)"
    try:
        m = json.loads(mf.read_text(encoding="utf-8"))
    except ValueError:
        return False, f"{MANIFEST} unreadable"
    if not _verify(_canonical(m.get("files", {})), m.get("signature", ""), public_hex):
        return False, "the manifest signature is not the owner's"
    if set(m["files"]) != set(PROTECTED):
        return False, "the manifest does not cover the protected files"
    changed = [f for f, h in m["files"].items() if not (root / f).exists() or _sha(root / f) != h]
    return (False, f"changed without the owner's signature: {', '.join(changed)}") if changed else (True, "intact")


CODE_PATTERNS = ("install.sh", "requirements.txt", "sys/core/**/*.py", "sys/core/**/*.js", "sys/core/**/*.css",
                 "sys/core/**/*.html", "sys/core/**/*.json", "sys/core/**/*.md", "sys/core/**/*.sh", "sys/plugins/*/*")


def code_files(root: Path = CODE_ROOT) -> list[str]:
    """Every file of the code base the owner signs as a whole (the second tier: changes are reported, not fatal)."""
    found = set()
    for pattern in CODE_PATTERNS:
        for p in root.glob(pattern):
            rel = p.relative_to(root).as_posix()
            if p.is_file() and "__pycache__" not in rel and rel not in (MANIFEST, "sys/core/ethics/exemption.sig"):
                found.add(rel)
    return sorted(found)


def code_drift(root: Path = CODE_ROOT, public_hex: str = "") -> dict:
    """{"changed", "added", "removed"} files against the signed code list; {"unsigned": reason} if there is none.
    The rules (PROTECTED) stop Aurora when changed; the rest of the code is made evident, so that a self-repair
    the owner approved does not stop her until he signs again."""
    if not public_hex:
        public_hex, problem = owner_public_key()
        if not public_hex:
            return {"unsigned": problem}
    try:
        m = json.loads((root / MANIFEST).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"unsigned": f"{MANIFEST} missing or unreadable"}
    code = m.get("code")
    if not code:
        return {"unsigned": "the manifest has no code list (sign again)"}
    if not _verify(_canonical(code), m.get("code_signature", ""), public_hex):
        return {"unsigned": "the code list is not signed by the owner"}
    now = set(code_files(root))
    return {"changed": sorted(f for f in now & set(code) if _sha(root / f) != code[f]),
            "added": sorted(now - set(code)), "removed": sorted(set(code) - now)}


def drift_summary(d: dict) -> str:
    if "unsigned" in d:
        return d["unsigned"]
    n = len(d["changed"]) + len(d["added"]) + len(d["removed"])
    return "" if not n else (f"{n} code files differ from the owner's signature: "
                             + ", ".join((d["changed"] + d["added"] + d["removed"])[:8]) + (" …" if n > 8 else ""))


def require_intact(log=None) -> None:
    """Every service calls this at start: rules changed without the owner mean no Aurora."""
    ok, reason = integrity()
    if not ok:
        msg = f"ethics code check failed: {reason}. Aurora does not start."
        if log:
            log.critical(msg)
        print(msg, file=sys.stderr)
        sys.exit(78)                                       # EX_CONFIG: systemd does not loop on it
    if log:
        log.info("ethics code: intact; level B %s", "exempted (owner)" if exempt() else "active")
        drift = drift_summary(code_drift())
        if drift:
            log.warning("code signature: %s", drift)


def machine_id() -> str:
    try:
        return Path("/etc/machine-id").read_text().strip()
    except OSError:
        return "unknown-machine"


def exemption_message(root: Path) -> bytes:
    return f"{EXEMPT_PURPOSE}|{machine_id()}|{root}".encode()


@lru_cache(maxsize=8)
def _exempt_cached(path: str, mtime: float, root: str, public_hex: str) -> bool:
    try:
        sig = Path(path).read_text().strip()
    except OSError:
        return False
    return _verify(exemption_message(Path(root)), sig, public_hex)


def exempt(cfg: sys_config.Config | None = None) -> bool:
    """Is this installation exempted from level B by the owner?"""
    cfg = cfg or sys_config.get()
    p = cfg.path("AURORA_ETHICS_EXEMPTION")
    public_hex, _ = owner_public_key()
    if not p.exists() or not public_hex:
        return False
    return _exempt_cached(str(p), p.stat().st_mtime, str(cfg.root), public_hex)


def forbidden_capabilities(manifest: dict) -> list[str]:
    """Level A: capabilities a plugin may never have."""
    return sorted(set(manifest.get("capabilities", [])) & FORBIDDEN)
