# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 A.U.R.O.R.A. Project
"""Generate the Caddyfile and the systemd units from .env, so they can never drift from it.

    <AURORA_HTTPS_DIR>/Caddyfile
    <AURORA_ROOT>/sys/deploy/systemd/aurora-{llm,models,api,https}.service + aurora.target

Units hold absolute paths written here and nothing else: they do not load .env
into the process environment (the code reads .env itself, and the API key would
otherwise be readable in /proc/<pid>/environ). After changing AURORA_ROOT,
ports, domain or certificates, run this again and reinstall the units.

    python sys/core/script/sys_install_services.py        # writes the files, validates the Caddyfile, prints the install commands
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from string import Template

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from aurora import sys_config  # noqa: E402

CADDYFILE = Template("""# Generated from .env by sys/core/script/sys_install_services.py — edit .env, not this file.
{
	admin $admin
	grace_period 5s
	auto_https disable_redirects
	http_port $http_port
	https_port $https_port
	log {
		output file $log_dir/caddy.log {
			roll_size ${max_mb}MiB
			roll_keep_for ${keep_hours}h
		}
		level INFO
	}
}

$domain:$https_port {
	tls $cert $key
	encode gzip zstd
	reverse_proxy $api {
		transport http {
			dial_timeout 10s
			read_timeout 900s
			write_timeout 900s
			response_header_timeout 900s
		}
		flush_interval -1
	}
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
		X-Frame-Options DENY
		Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; worker-src 'self'; manifest-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'"
		-Server
	}
}

http://$domain:$http_port {
	redir https://{host}$https_suffix{uri} permanent
}
""")

UNIT = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — $description
After=network-online.target $after
Wants=network-online.target $after
PartOf=aurora.target

[Service]
Type=simple
User=$user
WorkingDirectory=$root
ExecStart=$exec
Restart=on-failure
RestartSec=5
TimeoutStartSec=300
TimeoutStopSec=30
KillMode=mixed
KillSignal=SIGTERM
$extra
[Install]
WantedBy=aurora.target
""")

TARGET = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — all services
Wants=$wants
After=network-online.target

[Install]
WantedBy=multi-user.target
""")

# Lets the service user start, stop and restart Aurora's own units without a password
# prompt (and nothing else): the WebUI and the maintenance scripts restart services.
POLKIT = Template("""// Generated by sys/core/script/sys_install_services.py
polkit.addRule(function (action, subject) {
    if (action.id !== "org.freedesktop.systemd1.manage-units" || subject.user !== "$user") return;
    var unit = action.lookup("unit") || "";
    var verb = action.lookup("verb") || "";
    var ours = /^aurora(-[a-z]+)?\\.(service|target)$$/.test(unit);
    if (ours && ["start", "stop", "restart", "try-restart", "reload"].indexOf(verb) >= 0) return polkit.Result.YES;
});
""")


INSTALL = Template("""#!/usr/bin/env bash
# Generated by sys/core/script/sys_install_services.py: installs, (re)starts and checks Aurora's units.
set -u
[ "$$(id -u)" -eq 0 ] || { echo "run as root: sudo bash $$0"; exit 1; }
cd /
for u in $units; do install -m 0644 "$src/$$u" "/etc/systemd/system/$$u"; done
# polkit: the service user may start/stop/restart aurora units only (read again by polkit at once)
install -m 0644 "$src/50-aurora.rules" /etc/polkit-1/rules.d/50-aurora.rules
systemctl daemon-reload
systemctl reset-failed $units 2>/dev/null || true
systemctl enable $units
systemctl restart $services aurora.target

check() {  # name url: wait up to 180 s for a healthy answer
  for i in $$(seq 1 90); do
    if curl -fs --max-time 3 --resolve "$domain:$https_port:127.0.0.1" -o /dev/null "$$2"; then echo "  ok    $$1  $$2"; return 0; fi
    sleep 2
  done
  echo "  FAIL  $$1  $$2"; journalctl -u "$$1" -n 25 --no-pager; return 1
}
echo "checks:"
fail=0
$checks
for u in $services; do printf "  %-22s %s / %s\\n" "$$u" "$$(systemctl is-enabled $$u)" "$$(systemctl is-active $$u)"; done
exit $$fail
""")


def main() -> int:
    cfg = sys_config.get()
    root = cfg.root
    py = root / cfg["AURORA_VENV_DIR"] / "bin" / "python"
    script = cfg.path("AURORA_CORE_DIR") / "script"
    https_dir = cfg.path("AURORA_HTTPS_DIR")
    log_dir = cfg.path("AURORA_LOG_DIR") / "https"
    log_dir.mkdir(parents=True, exist_ok=True)

    caddyfile = https_dir / "Caddyfile"
    caddyfile.write_text(CADDYFILE.substitute(
        admin=cfg["AURORA_CADDY_ADMIN"], http_port=cfg["AURORA_HTTP_PORT"], https_port=cfg["AURORA_HTTPS_PORT"],
        https_suffix="" if cfg["AURORA_HTTPS_PORT"] == 443 else f":{cfg['AURORA_HTTPS_PORT']}",
        log_dir=log_dir, max_mb=cfg["AURORA_LOG_MAX_MB"], keep_hours=cfg["AURORA_LOG_RETENTION_DAYS"] * 24,
        domain=cfg["AURORA_DOMAIN"], cert=cfg.path("AURORA_TLS_CERT"), key=cfg.path("AURORA_TLS_KEY"),
        api=f"{cfg['AURORA_API_HOST']}:{cfg['AURORA_API_PORT']}"), encoding="utf-8")
    check = subprocess.run([cfg["AURORA_CADDY_BIN"], "validate", "--config", str(caddyfile), "--adapter", "caddyfile"],
                           capture_output=True, text=True)
    print(f"{caddyfile}: {'valid' if check.returncode == 0 else 'INVALID'}")
    if check.returncode != 0:
        print(check.stderr[-2000:])
        return 1

    low_ports = min(cfg["AURORA_HTTPS_PORT"], cfg["AURORA_HTTP_PORT"]) < 1024
    units = {
        "aurora-llm": ("reasoner (llama.cpp)", "", f"{py} {script / 'svc_llm.py'}", ""),
        "aurora-models": ("encoder and re-ranker", "", f"{py} {script / 'svc_models.py'}", ""),
        "aurora-api": ("API, events and WebUI", "aurora-models.service aurora-llm.service",
                       f"{py} {script / 'svc_api.py'}", ""),
        "aurora-rem": ("autonomic cycle (consolidation, reflections, dreams)", "aurora-api.service",
                       f"{py} {script / 'svc_rem.py'}", ""),
        "aurora-harvester": ("harvester (new knowledge)", "aurora-api.service",
                             f"{py} {script / 'svc_harvester.py'}", ""),
        "aurora-sentinel": ("sentinel (firewall syslog, incidents)", "aurora-api.service",
                            f"{py} {script / 'svc_sentinel.py'}", ""),
        "aurora-https": ("HTTPS (Caddy)", "aurora-api.service",
                         f"{cfg['AURORA_CADDY_BIN']} run --config {caddyfile} --adapter caddyfile",
                         f"ExecReload={cfg['AURORA_CADDY_BIN']} reload --config {caddyfile} --adapter caddyfile --force\n"
                         + ("AmbientCapabilities=CAP_NET_BIND_SERVICE\n" if low_ports else "")),
    }
    out = root / "sys" / "deploy" / "systemd"
    out.mkdir(parents=True, exist_ok=True)
    for name, (desc, after, exec_, extra) in units.items():
        (out / f"{name}.service").write_text(UNIT.substitute(
            description=desc, after=after, user=cfg["AURORA_SERVICE_USER"], root=root, exec=exec_, extra=extra),
            encoding="utf-8")
    (out / "aurora.target").write_text(TARGET.substitute(wants=" ".join(f"{n}.service" for n in units)),
                                       encoding="utf-8")
    (out / "50-aurora.rules").write_text(POLKIT.substitute(user=cfg["AURORA_SERVICE_USER"]), encoding="utf-8")
    print(f"units written to {out}:")
    for p in sorted(out.iterdir()):
        print(f"  {p.name}")
    # Explicit unit names on purpose: `systemctl enable aurora-*` matches only units already
    # loaded in memory, so on a fresh install it silently does nothing.
    names = [f"{n}.service" for n in units] + ["aurora.target"]
    checks = {"aurora-models": f"http://{cfg['AURORA_MODELS_HOST']}:{cfg['AURORA_MODELS_PORT']}/health",
              "aurora-llm": f"http://{cfg['AURORA_LLM_HOST']}:{cfg['AURORA_LLM_PORT']}/health",
              "aurora-api": f"http://{cfg['AURORA_API_HOST']}:{cfg['AURORA_API_PORT']}/health",
              "aurora-https": f"https://{cfg['AURORA_DOMAIN']}:{cfg['AURORA_HTTPS_PORT']}/"}
    script_sh = out / "install.sh"
    script_sh.write_text(INSTALL.substitute(
        src=out, units=" ".join(names), services=" ".join(f"{n}.service" for n in units),
        checks="\n".join(f"check {n} {u} || fail=1" for n, u in checks.items()),
        https_port=cfg["AURORA_HTTPS_PORT"], domain=cfg["AURORA_DOMAIN"]), encoding="utf-8")
    script_sh.chmod(0o755)
    print(f"\ninstall, start and check (as root):\n  sudo bash {script_sh}")
    print(f"\nthen: https://{cfg['AURORA_DOMAIN']}" + ("" if cfg["AURORA_HTTPS_PORT"] == 443 else f":{cfg['AURORA_HTTPS_PORT']}") + "/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
