# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 A.U.R.O.R.A. Project
"""Generate the Caddyfile and the systemd units from .env, so they can never drift from it.

    <AURORA_HTTPS_DIR>/Caddyfile
    <AURORA_ROOT>/sys/deploy/systemd/aurora-{llm,models,api,https}.service + aurora.target

Units hold absolute paths written here and nothing else: they do not load .env
into the process environment (the code reads .env itself, and the API key would
otherwise be readable in /proc/<pid>/environ). After changing AURORA_ROOT,
ports, domain or certificates, run this again and reinstall the units.

    python sys/core/script/sys_install_services.py        # writes the files, validates the Caddyfile, prints the install commands
"""
from __future__ import annotations

import sys
from pathlib import Path
from string import Template

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from aurora import sys_config  # noqa: E402


UNIT = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — $description
After=network-online.target $after
Wants=network-online.target $after
PartOf=aurora.target

[Service]
Type=simple
User=$user
WorkingDirectory=$root
ExecStart=$exec
Restart=on-failure
RestartSec=5
TimeoutStartSec=300
TimeoutStopSec=30
KillMode=mixed
KillSignal=SIGTERM
$extra
[Install]
WantedBy=aurora.target
""")

# The nightly backup: a oneshot started by its timer (not part of aurora.target: it runs and ends), low priority for
# the disk and the CPU, allowed to write only Aurora's folder and the backup folder.
BACKUP_UNIT = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — backup of the owner's data (encrypted, to $dest)
After=aurora-api.service remote-fs.target$order
# a NAS asleep at night: tried again every 20 minutes, 4 times; then the failure is told by a unit of its own,
# since a backup that cannot reach its folder cannot even start (status 226/NAMESPACE, A18)
StartLimitIntervalSec=2h
StartLimitBurst=4
OnFailure=aurora-backup-failed.service

[Service]
Type=oneshot
User=$user
WorkingDirectory=$root
ExecStart=$exec
Nice=15
IOSchedulingClass=idle
MemoryHigh=2G
TimeoutStartSec=6h
Restart=on-failure
RestartSec=20min
$extra""")

# The backup's failure told to the owner (push, WebUI): no access to the backup folder, so it runs when that is gone.
BACKUP_FAILED_UNIT = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — tell the owner that the backup failed

[Service]
Type=oneshot
User=$user
WorkingDirectory=$root
ExecStart=$exec
TimeoutStartSec=60
$extra""")

BACKUP_TIMER = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — nightly backup at $time

[Timer]
OnCalendar=*-*-* $time:00
Persistent=true
RandomizedDelaySec=120

[Install]
WantedBy=timers.target
""")

# Root, on purpose and for one job: mount the backup's NAS share (sys_nas_mount.py checks every value it writes).
# Started by the API when the backup plugin is saved (polkit: the service user may start aurora units).
MOUNT_UNIT = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — mount the backup's NAS share (/mnt/aurora-nas)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
WorkingDirectory=$root
ExecStart=$exec
TimeoutStartSec=180
NoNewPrivileges=yes
ProtectHome=read-only
ReadWritePaths=-$status
PrivateTmp=yes
""")

# Root, on purpose and for one job: move the backup timer to AURORA_BACKUP_TIME (sys_backup_retime.py checks HH:MM
# and writes one drop-in). Started by the API when the backup time is saved (polkit: aurora units).
RETIME_UNIT = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — move the nightly backup to AURORA_BACKUP_TIME

[Service]
Type=oneshot
User=root
WorkingDirectory=$root
ExecStart=$exec
TimeoutStartSec=60
NoNewPrivileges=yes
ProtectHome=read-only
PrivateTmp=yes
""")

TARGET = Template("""# Generated from .env by sys/core/script/sys_install_services.py
[Unit]
Description=Aurora — all services
Wants=$wants
After=network-online.target

[Install]
WantedBy=multi-user.target
""")

# Lets the service user start, stop and restart Aurora's own units without a password
# prompt (and nothing else): the WebUI and the maintenance scripts restart services.
POLKIT = Template("""// Generated by sys/core/script/sys_install_services.py
polkit.addRule(function (action, subject) {
    if (action.id !== "org.freedesktop.systemd1.manage-units" || subject.user !== "$user") return;
    var unit = action.lookup("unit") || "";
    var verb = action.lookup("verb") || "";
    var ours = /^aurora(-[a-z]+)?\\.(service|target)$$/.test(unit);
    if (ours && ["start", "stop", "restart", "try-restart", "reload"].indexOf(verb) >= 0) return polkit.Result.YES;
});
""")


INSTALL = Template("""#!/usr/bin/env bash
# Generated by sys/core/script/sys_install_services.py: installs, (re)starts and checks Aurora's units.
set -u
[ "$$(id -u)" -eq 0 ] || { echo "run as root: sudo bash $$0"; exit 1; }
cd /
for u in $units $backup; do install -m 0644 "$src/$$u" "/etc/systemd/system/$$u"; done
# polkit: the service user may start/stop/restart aurora units only (read again by polkit at once)
install -m 0644 "$src/50-aurora.rules" /etc/polkit-1/rules.d/50-aurora.rules
systemctl daemon-reload
systemctl reset-failed $units 2>/dev/null || true
systemctl enable $units
[ -n "$backup" ] && systemctl enable --now aurora-backup.timer && echo "  backup timer: $$(systemctl show -p NextElapseUSecRealtime --value aurora-backup.timer)"
case " $backup " in *" aurora-mount.service "*)
  systemctl start aurora-mount.service && echo "  NAS: mounted on /mnt/aurora-nas" || echo "  NAS: not mounted yet (user/password in the backup plugin's card, then Save)";;
esac
systemctl restart $services aurora.target

check() {  # name url: wait up to 180 s for a healthy answer (alive: whether the browser trusts the certificate is
  # another matter, and a new machine trusts Caddy's local authority only after this script, with caddy trust: C212)
  for i in $$(seq 1 90); do
    if curl -fsk --max-time 3 --resolve "$domain:$https_port:127.0.0.1" -o /dev/null "$$2"; then echo "  ok    $$1  $$2"; return 0; fi
    sleep 2
  done
  echo "  FAIL  $$1  $$2"; journalctl -u "$$1" -n 25 --no-pager; return 1
}
echo "checks:"
fail=0
$checks
for u in $services; do printf "  %-22s %s / %s\\n" "$$u" "$$(systemctl is-enabled $$u)" "$$(systemctl is-active $$u)"; done
exit $$fail
""")


def hardening(root: Path, user: str, bind_low_port: bool, hosts_plugins: bool = False, also: tuple = ()) -> str:
    """systemd confinement: the system read-only, the home read-only but for what a service writes, no new
    privileges, no capabilities (Caddy keeps only the one to open ports below 1024), kernel and clock protected.
    Devices stay visible: the GPUs and the camera are devices. A "-" path may be missing.
    The unit that hosts the plugins (aurora-api) keeps /proc whole: ProtectKernelTunables/ProtectKernelLogs/
    ProtectHostname mount over parts of /proc, and the kernel then refuses the plugin cage (bubblewrap) its own /proc
    ("Can't mount proc ... Operation not permitted"): no plugin would start."""
    import pwd
    home = Path(pwd.getpwnam(user).pw_dir)
    writable = [str(root), f"-{home}/.cache", f"-{home}/.local/share/caddy", f"-{home}/.config/caddy",
                f"-{home}/.claude", f"-{home}/.claude.json", f"-{home}/.ssh/known_hosts", *also]
    caps = "CAP_NET_BIND_SERVICE" if bind_low_port else ""
    # the owner's private SSH keys (an account key can write to every repository he has): no service needs them
    ssh = home / ".ssh"
    hidden = sorted(f"-{f}" for f in (ssh.iterdir() if ssh.is_dir() else []) if f.is_file()
                    and not f.name.endswith(".pub") and not f.name.startswith(("known_hosts", "config", "authorized_keys")))
    return ("# confinement (AURORA_SERVICE_HARDENING)\n"
            "NoNewPrivileges=yes\nProtectSystem=strict\nProtectHome=read-only\n"
            f"ReadWritePaths={' '.join(writable)}\nPrivateTmp=yes\n"
            + (f"InaccessiblePaths={' '.join(hidden)}\n" if hidden else "")
            + f"CapabilityBoundingSet={caps}\nRestrictSUIDSGID=yes\nLockPersonality=yes\nRestrictRealtime=yes\n"
            + ("" if hosts_plugins else "ProtectKernelTunables=yes\nProtectKernelLogs=yes\nProtectHostname=yes\n")
            # read-only vault connections are cached per thread: ~50 pooled threads x 37 shards x 3 files can pass
            # the default 1024 (C103)
            + ("LimitNOFILE=8192\n" if hosts_plugins else "")
            + "ProtectKernelModules=yes\nProtectControlGroups=yes\n"
            "ProtectClock=yes\nSystemCallArchitectures=native\n"
            "RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK\nUMask=0077\n")


def main() -> int:
    cfg = sys_config.get()
    root = cfg.root
    py = root / cfg["AURORA_VENV_DIR"] / "bin" / "python"
    script = cfg.path("AURORA_CORE_DIR") / "script"
    from aurora import net_https                       # the Caddyfile is the HTTPS page's too (one writer)
    try:
        caddyfile = net_https.write(cfg)
    except net_https.HttpsError as e:
        print(f"{net_https.caddyfile(cfg)}: INVALID\n{e}")
        return 1
    print(f"{caddyfile}: valid")

    low_ports = min(cfg["AURORA_HTTPS_PORT"], cfg["AURORA_HTTP_PORT"]) < 1024
    cloud = str(cfg["AURORA_LLM_BACKEND"]) == "cloud"      # no local reasoner: no aurora-llm (the installer chose it)
    units = {
        "aurora-llm": ("reasoner (llama.cpp)", "", f"{py} {script / 'svc_llm.py'}", ""),
        "aurora-models": ("encoder and re-ranker", "", f"{py} {script / 'svc_models.py'}", ""),
        "aurora-api": ("API, events and WebUI", "aurora-models.service" + ("" if cloud else " aurora-llm.service"),
                       f"{py} {script / 'svc_api.py'}", ""),
        "aurora-rem": ("autonomic cycle (consolidation, reflections, dreams)", "aurora-api.service",
                       f"{py} {script / 'svc_rem.py'}", ""),
        "aurora-harvester": ("harvester (new knowledge)", "aurora-api.service",
                             f"{py} {script / 'svc_harvester.py'}", ""),
        "aurora-sentinel": ("sentinel (firewall syslog, incidents)", "aurora-api.service",
                            f"{py} {script / 'svc_sentinel.py'}", ""),
        "aurora-https": ("HTTPS (Caddy)", "aurora-api.service",
                         f"{cfg['AURORA_CADDY_BIN']} run --config {caddyfile} --adapter caddyfile",
                         f"ExecReload={cfg['AURORA_CADDY_BIN']} reload --config {caddyfile} --adapter caddyfile --force\n"
                         + ("AmbientCapabilities=CAP_NET_BIND_SERVICE\n" if low_ports else "")),
    }
    if cloud:
        del units["aurora-llm"]
    out = root / "sys" / "deploy" / "systemd"
    out.mkdir(parents=True, exist_ok=True)
    stale = out / "aurora-llm.service"
    if cloud and stale.exists():                       # written when this machine had a local reasoner
        stale.unlink()
    for name, (desc, after, exec_, extra) in units.items():
        if cfg["AURORA_SERVICE_HARDENING"]:
            extra += hardening(root, sys_config.service_user(cfg), name == "aurora-https" and low_ports,
                               hosts_plugins=name == "aurora-api")
        (out / f"{name}.service").write_text(UNIT.substitute(
            description=desc, after=after, user=sys_config.service_user(cfg), root=root, exec=exec_, extra=extra),
            encoding="utf-8")
    backup = []                                        # only when a backup folder is set
    dest = str(cfg["AURORA_BACKUP_DIR"] or "").strip()
    if dest:
        import re
        hhmm = str(cfg["AURORA_BACKUP_TIME"]).strip()
        if not re.fullmatch(r"([01]\d|2[0-3]):[0-5]\d", hhmm):
            print(f"AURORA_BACKUP_TIME {hhmm!r} is not HH:MM")
            return 1
        writable = "/mnt/aurora-nas" if dest.startswith("smb://") else dest
        extra = hardening(root, sys_config.service_user(cfg), False, also=(writable,)) if cfg["AURORA_SERVICE_HARDENING"] else ""
        (out / "aurora-backup.service").write_text(BACKUP_UNIT.substitute(
            dest=dest, user=sys_config.service_user(cfg), root=root, exec=f"{py} {script / 'svc_backup.py'} run",
            # C123: a timer's catch-up run started 1 s before the NAS was mounted and wrote into the bare folder
            order=("\nWants=aurora-mount.service\nAfter=aurora-mount.service" if dest.startswith("smb://") else ""),
            extra=extra), encoding="utf-8")
        (out / "aurora-backup.timer").write_text(BACKUP_TIMER.substitute(time=hhmm), encoding="utf-8")
        (out / "aurora-backup-failed.service").write_text(BACKUP_FAILED_UNIT.substitute(
            user=sys_config.service_user(cfg), root=root, exec=f"{py} {script / 'svc_backup.py'} failed",
            extra=hardening(root, sys_config.service_user(cfg), False) if cfg["AURORA_SERVICE_HARDENING"] else ""),
            encoding="utf-8")
        (out / "aurora-retime.service").write_text(RETIME_UNIT.substitute(
            root=root, exec=f"{py} {script / 'sys_backup_retime.py'}"), encoding="utf-8")
        backup = ["aurora-backup.service", "aurora-backup.timer", "aurora-backup-failed.service", "aurora-retime.service"]
        if dest.startswith("smb://"):
            (cfg.path("AURORA_STATUS_DIR") / "backup").mkdir(parents=True, exist_ok=True)
            (out / "aurora-mount.service").write_text(MOUNT_UNIT.substitute(
                root=root, exec=f"{py} {script / 'sys_nas_mount.py'}",
                status=cfg.path("AURORA_STATUS_DIR") / "backup"), encoding="utf-8")
            backup.append("aurora-mount.service")
    (out / "aurora.target").write_text(TARGET.substitute(wants=" ".join(f"{n}.service" for n in units)),
                                       encoding="utf-8")
    (out / "50-aurora.rules").write_text(POLKIT.substitute(user=sys_config.service_user(cfg)), encoding="utf-8")
    print(f"units written to {out}:")
    for p in sorted(out.iterdir()):
        print(f"  {p.name}")
    # Explicit unit names on purpose: `systemctl enable aurora-*` matches only units already
    # loaded in memory, so on a fresh install it silently does nothing.
    names = [f"{n}.service" for n in units] + ["aurora.target"]
    checks = {"aurora-models": f"http://{cfg['AURORA_MODELS_HOST']}:{cfg['AURORA_MODELS_PORT']}/health",
              **({} if cloud else {"aurora-llm": f"http://{cfg['AURORA_LLM_HOST']}:{cfg['AURORA_LLM_PORT']}/health"}),
              "aurora-api": f"http://{cfg['AURORA_API_HOST']}:{cfg['AURORA_API_PORT']}/health",
              "aurora-https": f"https://{cfg['AURORA_DOMAIN']}:{cfg['AURORA_HTTPS_PORT']}/"}
    script_sh = out / "install.sh"
    script_sh.write_text(INSTALL.substitute(
        src=out, units=" ".join(names), services=" ".join(f"{n}.service" for n in units), backup=" ".join(backup),
        checks="\n".join(f"check {n} {u} || fail=1" for n, u in checks.items()),
        https_port=cfg["AURORA_HTTPS_PORT"], domain=cfg["AURORA_DOMAIN"]), encoding="utf-8")
    script_sh.chmod(0o755)
    print(f"\ninstall, start and check (as root):\n  sudo bash {script_sh}")
    print(f"\nthen: https://{cfg['AURORA_DOMAIN']}" + ("" if cfg["AURORA_HTTPS_PORT"] == 443 else f":{cfg['AURORA_HTTPS_PORT']}") + "/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
