# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 A.U.R.O.R.A. Project
"""Move the nightly backup to AURORA_BACKUP_TIME — run as root by aurora-retime.

    systemctl start aurora-retime.service       # what saving the backup time does (polkit: aurora units only)

The timer in /etc/systemd/system is written once by install.sh; without this a new time in the settings changed
nothing (the page kept showing the old one). What root does, and nothing else:
  - the time is checked strictly (HH:MM), nothing else is read from the settings;
  - one drop-in, /etc/systemd/system/aurora-backup.timer.d/time.conf, replaces the timer's OnCalendar;
  - systemd reloads, the timer restarts; the next run is printed (journal).
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

DROPIN = Path("/etc/systemd/system/aurora-backup.timer.d/time.conf")
HHMM = re.compile(r"([01]\d|2[0-3]):[0-5]\d")


def dropin(hhmm: str) -> str:
    """The drop-in for a checked time; ValueError for anything that is not HH:MM."""
    if not HHMM.fullmatch(hhmm):
        raise ValueError(f"AURORA_BACKUP_TIME {hhmm!r} is not HH:MM")
    return ("# Generated by sys/core/script/sys_backup_retime.py from AURORA_BACKUP_TIME\n"
            f"[Unit]\nDescription=Aurora — nightly backup at {hhmm}\n\n"
            f"[Timer]\nOnCalendar=\nOnCalendar=*-*-* {hhmm}:00\n")


def main() -> int:
    from aurora import sys_config
    try:
        text = dropin(str(sys_config.get()["AURORA_BACKUP_TIME"]).strip())
    except ValueError as e:
        print(e)
        return 1
    DROPIN.parent.mkdir(parents=True, exist_ok=True)
    DROPIN.write_text(text, encoding="utf-8")
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "restart", "aurora-backup.timer"], check=True)
    nxt = subprocess.run(["systemctl", "show", "-p", "NextElapseUSecRealtime", "--value", "aurora-backup.timer"],
                         capture_output=True, text=True).stdout.strip()
    print(f"backup timer: next {nxt}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
